### ISSUE TITLE
PhpStorm не видит запросы 

### ISSUE THREAD

**Issue by alexdontsov** [ITReviewChannel/xdebug-docker-phpstorm#1]
Здравствуйте! Пробую по вашему реководству настроить Xdebug, всё сделал аналогично, но PHPStorm не отлавливает запросы. Нужно ли что-то дополнительно настраивать?

**Comment by ITReviewChannel** [comment]
Добрый день! Тут вроде бы ничего не забыл: [itreviewchannel.ru/nastrojka-xdebug-3-docker-phpstorm](https://itreviewchannel.ru/nastrojka-xdebug-3-docker-phpstorm/). Хотя есть догадка, у вас PhpStorm успешно с Docker'ом соединяется? Рецепт по ссылке выше обновил, выложил скрины.

На всякий случай проверьте список возможных проблем, он такой:

- поддерживает ли текущая версия PhpStorm'a используемую версию отладчика (для xDebug'a >= 3 нужна версия >= 2020.3)
- прописано ли имя сервера в настройках PhpStorm'a
- запущен ли режим ожидания запроса и выставлены ли точки остановки
- нормально ли работает xDebug, это можно посмотреть в консоли "php -v" или "php -m" (в списке модулей он должен быть)
- верно ли прописаны настройки в php.ini (если используется Linux, то вместо host.docker.internal необходимо указать IP сети из команды ifconfig)

**Comment by ITReviewChannel** [comment]
Получилось настроить?

**Comment by alexdontsov** [comment]
Здравствуйте! ДА, спасибо большое заработало. Проблема была в php.ini, туда прописал ip сети из команды ifconfig
